---
http_interactions:
- request:
    method: put
    uri: https://gs-gem-test-suite-080e34c0-0b79-0130-7a1c-0023dfa5d78c.commondatastorage.googleapis.com/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
      host:
      - gs-gem-test-suite-080e34c0-0b79-0130-7a1c-0023dfa5d78c.commondatastorage.googleapis.com
      date:
      - Thu, 08 Nov 2012 02:22:13 GMT
      content-type:
      - binary/octet-stream
      content-length:
      - '0'
      x-goog-api-version:
      - 2
      x-goog-project-id:
      - 459171454079
      authorization:
      - Bearer ____SILENCED_access_token____
      x-goog-acl:
      - public-read
  response:
    status:
      code: 200
      message: OK
    headers:
      server:
      - HTTP Upload Server Built on Oct 3 2012 16:52:30 (1349308350)
      vary:
      - Origin
      date:
      - Thu, 08 Nov 2012 02:22:15 GMT
      pragma:
      - no-cache
      expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      cache-control:
      - no-cache, no-store, must-revalidate
      content-length:
      - '0'
      content-type:
      - text/html; charset=UTF-8
    body:
      encoding: US-ASCII
      string: ''
    http_version: '1.1'
  recorded_at: Thu, 08 Nov 2012 02:22:15 GMT
- request:
    method: put
    uri: https://gs-gem-test-suite-080e34c0-0b79-0130-7a1c-0023dfa5d78c.commondatastorage.googleapis.com/?websiteConfig
    body:
      encoding: US-ASCII
      string: <WebsiteConfiguration><MainPageSuffix>index.html</MainPageSuffix><NotFoundPage>404.html</NotFoundPage></WebsiteConfiguration>
    headers:
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
      host:
      - gs-gem-test-suite-080e34c0-0b79-0130-7a1c-0023dfa5d78c.commondatastorage.googleapis.com
      date:
      - Thu, 08 Nov 2012 02:22:15 GMT
      content-type:
      - binary/octet-stream
      content-length:
      - '125'
      x-goog-api-version:
      - 2
      authorization:
      - Bearer ____SILENCED_access_token____
  response:
    status:
      code: 200
      message: OK
    headers:
      server:
      - HTTP Upload Server Built on Oct 3 2012 16:52:30 (1349308350)
      vary:
      - Origin
      date:
      - Thu, 08 Nov 2012 02:22:16 GMT
      pragma:
      - no-cache
      expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      cache-control:
      - no-cache, no-store, must-revalidate
      content-length:
      - '0'
      content-type:
      - text/html; charset=UTF-8
    body:
      encoding: US-ASCII
      string: ''
    http_version: '1.1'
  recorded_at: Thu, 08 Nov 2012 02:22:16 GMT
recorded_with: VCR 2.3.0
